### PR TITLE
chore: update multihashing-async dep

### PR DESCRIPTION
**Pull request by alanshaw**
@vasco-santos @jacobheun do you have any plans to add automated dependency updating?

### CODE REVIEW

**Comment by vasco-santos** [comment]
We did not discuss that topic yet, but I think that we should discuss this! Maybe an agenda item for the JS office hours?

**Comment by vasco-santos** [comment]
@alanshaw I added a commit to fix the linter and just got the opportunity to update the remaining dependencies.

**Comment by alanshaw** [comment]
> We did not discuss that topic yet, but I think that we should discuss this! Maybe an agenda item for the JS office hours?

That would be rad, for reference, I opened the following PRs recently in the libp2p world to update some out of range dependencies that were published months ago:

* https://github.com/libp2p/js-libp2p-crypto-secp256k1/pull/19
* https://github.com/libp2p/js-peer-info/pull/84
* https://github.com/libp2p/js-libp2p-webrtc-star/pull/192
* https://github.com/libp2p/js-libp2p-keychain/pull/40
* and of course this one 😄 https://github.com/libp2p/js-libp2p-record/pull/17
* ...maybe some more I missed!

**Comment by vasco-santos** [comment]
You are absolutely right! Let's define this next week :)

**Pull request merged**
